In [7]:
import numpy as np

In [11]:
np.__version__

'1.18.5'

In [12]:
L = list(range(10))

In [13]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
type(L)

list

In [16]:
type(L[0])

int

In [17]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [18]:
type(L2)

list

In [19]:
type(L2[4])

str

In [20]:
L3 = [ True,"3",4.56,9]

In [24]:
type(L3[3])

int

In [26]:
[type(item) for item in L3]

[bool, str, float, int]

In [30]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [37]:
np.ones((5,6),dtype=float)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
np.full((4,4),8.93)

array([[8.93, 8.93, 8.93, 8.93],
       [8.93, 8.93, 8.93, 8.93],
       [8.93, 8.93, 8.93, 8.93],
       [8.93, 8.93, 8.93, 8.93]])

In [41]:
np.full((2,2),"P")

array([['P', 'P'],
       ['P', 'P']], dtype='<U1')

In [45]:
#array filled with linear sequence starting with 0 till 36 in steps of 3
np.arange(0,36,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [62]:
#array of 8 values evenly spaced between 2 & 8
np.linspace(2,8,8)

array([2.        , 2.85714286, 3.71428571, 4.57142857, 5.42857143,
       6.28571429, 7.14285714, 8.        ])

In [51]:
#uniformly distributed random values between 0 & 1
np.random.random((5,4))

array([[0.36298242, 0.43215298, 0.44304639, 0.38492883],
       [0.89329823, 0.06543153, 0.65199465, 0.02653082],
       [0.111857  , 0.31552402, 0.90861454, 0.81645496],
       [0.99317795, 0.21738464, 0.88369958, 0.80133977],
       [0.20988431, 0.14448813, 0.23009287, 0.34976079]])

In [52]:
#3x3 array of normally distributed random values with mean 0 & std dev 1
np.random.normal(0,1,(3,3))

array([[ 0.0581978 , -0.35271274,  0.23161271],
       [ 0.52601165, -0.83654915, -0.33688842],
       [-0.59760425, -0.42121411,  1.16592589]])

In [57]:
#another eg of the above
np.random.normal(2.3, 1.86,(6,6))


array([[ 2.2374349 , -0.64433585,  2.32551511,  4.32794739,  0.24091814,
         2.82164871],
       [ 0.30968986,  3.28226406,  2.80767622,  4.54786683,  0.92978096,
        -1.07849471],
       [ 0.83566482,  5.6018481 ,  3.93656961, -1.07661919,  4.2397402 ,
        -1.08347316],
       [ 3.74853138,  1.70547353,  1.42364654,  3.10378663,  4.5256738 ,
         1.19203362],
       [-1.71709803, -0.53827883,  2.00266045,  0.35794794,  4.04665936,
         1.5767279 ],
       [ 4.81213855,  1.79900081, -1.41538109,  0.62063335,  4.84328806,
         4.44824125]])

In [64]:
#4x4 array with random integers between 2 & 7
np.random.randint(2,7,(4,4))

array([[3, 4, 3, 4],
       [4, 6, 3, 3],
       [2, 6, 5, 4],
       [6, 4, 5, 4]])

In [66]:
#to create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
np.empty(2)

array([9.11036106e-312, 0.00000000e+000])